services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TRAW\Powermailcaptcha\:
    resource: '../Classes/*'

  TRAW\Powermailcaptcha\EventListener\PowermailFormControllerFormActionEventListener:
    tags:
      - name: event.listener
        method: handleEvent
        identifier: 'powermailcaptchaFormControllerFormActionEventListener'